# require ---------------------------------------
require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

# main ------------------------------------------
AllCops:
  Exclude:
    # 自動生成は除外する
    - db/*schema.rb
    - node_modules/**/*
    - vendor/**/*
  TargetRubyVersion: 2.6

# Layout ----------------------------------------
# ハッシュはtable,key両方許容
Layout/AlignHash:
  EnforcedColonStyle:
    - table
    - key
  EnforcedHashRocketStyle:
    - table
    - key

# クラスの定義順に規約をいれる
# https://github.com/rubocop-hq/ruby-style-guide#consistent-classes
Layout/ClassStructure:
  Enabled: true

# return if hoge? のあとは行を空けなくてもよい
Layout/EmptyLineAfterGuardClause:
  Enabled: false

# Metrics ---------------------------------------
Metrics/AbcSize:
  Max: 16

Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
    - config/routes.rb
    - config/routes/**/*.rb
    - spec/**/*_spec.rb
    - spec/factories/*

Metrics/LineLength:
  Exclude:
    - db/migrate/*.rb
  Max: 120

Metrics/ParameterLists:
  # キーワード引数の数に制限を設けない
  CountKeywordArgs: false

# Style ----------------------------------------
# 引数のハッシュはよしなにする
Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    find: 'detect'     # ActiveRecordのfindのイメージが強いので変える
    find_all: 'filter' # ruby2.6以降は多言語にあわせfilterを使っていきたい

# nested は事故るので false にする
Style/ClassAndModuleChildren:
  Enabled: false

# コメントがないクラスも許可する
Style/Documentation:
  Enabled: false

# 複数行の場合はカンマをいれる。
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

# Rails -----------------------------------------
# 文字数が揃わなくなるので 1.days を受け入れる
Rails/PluralizationGrammar:
  Enabled: false

# RSpec -----------------------------------------
# when や without などの predix がなくても許可する
# 日本語の「〜場合」に対応したら考える
# https://github.com/rubocop-hq/rubocop-rspec/issues/745
RSpec/ContextWording:
  Enabled: false

# 階層が深くなるのをデフォルトよりもゆるくする。
# 無理に守ると逆に読みにくくなる。数値は要検討
RSpec/NestedGroups:
  Max: 5

