version: '3'
services:
  web:
    tty: true
    stdin_open: true
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "./:/work:cached"
      - "./vendor/bundle:/usr/local/bundle:cached"
      - "/work/.git"
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    volumes:
      - "db:/var/lib/postgresql/data"
volumes:
  db: {}
