version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - "./:/work"
      #- "bundle-data:bundle"
      - "./docker_tmp/bundle_data:/bundle"
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - "./docker_tmp/pgdata:/var/lib/postgresql/data"
# volumes:
#   bundle-data:
#   db-data:
