# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

defaults: &defaults
  docker:
    # specify the version you desire here
    - image: circleci/ruby:2.6.4-node-browsers
      environment:
        DB_HOST: 127.0.0.1
        RAILS_ENV: test

    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    - image: circleci/postgres:11-alpine
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: work_test
        POSTGRES_PASSWORD: ""

  working_directory: ~/repo

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            gem install bundler -v 2.0.2 &&
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: rm ./config/database.yml
      - run: mv ./config/database.ci.yml ./config/database.yml
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./*

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - run:
          command: |
            gem install bundler -v 2.0.2
      - run:
          name: bundle config
          command: |
            bundle config --local path vendor/bundle
      # run tests!
      - run:
          name: run tests
          command: |
            bundle exec rspec

  rubocop:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-
      - run:
          command: |
            gem install bundler -v 2.0.2
      - run:
          name: bundle config
          command: |
            bundle config --local path vendor/bundle
      # run rubocop
      - run:
          name: run rubocop
          command: |
            bundle exec rubocop

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - rubocop:
          requires:
            - build
